spring:
  #\u6570\u636E\u6E90\u914D\u7F6E
  data:
    mongodb:
      # \u6570\u636E\u5E93
      database: articledb
      # \u4E5F\u53EF\u4EE5\u4F7F\u7528uri\u8FDE\u63A5
      uri: mongodb://root:123456@localhost:27017
